name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release Github
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Build
          path: build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/*'
